// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aluno.proto

package br.ufs.dcomp.ExemploProtocolBuffers;

public final class ContatoProto {
  private ContatoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public enum Tipo
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MOVEL = 0;</code>
     */
    MOVEL(0),
    /**
     * <code>CASA = 1;</code>
     */
    CASA(1),
    /**
     * <code>TRABALHO = 2;</code>
     */
    TRABALHO(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MOVEL = 0;</code>
     */
    public static final int MOVEL_VALUE = 0;
    /**
     * <code>CASA = 1;</code>
     */
    public static final int CASA_VALUE = 1;
    /**
     * <code>TRABALHO = 2;</code>
     */
    public static final int TRABALHO_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Tipo valueOf(int value) {
      return forNumber(value);
    }

    public static Tipo forNumber(int value) {
      switch (value) {
        case 0: return MOVEL;
        case 1: return CASA;
        case 2: return TRABALHO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Tipo>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Tipo> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Tipo>() {
            public Tipo findValueByNumber(int number) {
              return Tipo.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final Tipo[] VALUES = values();

    public static Tipo valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Tipo(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ExemploProtocolBuffers.Tipo)
  }

  public interface AlunoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ExemploProtocolBuffers.Aluno)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 matricula = 1;</code>
     */
    int getMatricula();

    /**
     * <code>string nome = 2;</code>
     */
    java.lang.String getNome();
    /**
     * <code>string nome = 2;</code>
     */
    com.google.protobuf.ByteString
        getNomeBytes();

    /**
     * <code>string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
     */
    java.util.List<br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone> 
        getTelefonesList();
    /**
     * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
     */
    br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone getTelefones(int index);
    /**
     * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
     */
    int getTelefonesCount();
    /**
     * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
     */
    java.util.List<? extends br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.TelefoneOrBuilder> 
        getTelefonesOrBuilderList();
    /**
     * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
     */
    br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.TelefoneOrBuilder getTelefonesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ExemploProtocolBuffers.Aluno}
   */
  public  static final class Aluno extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ExemploProtocolBuffers.Aluno)
      AlunoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Aluno.newBuilder() to construct.
    private Aluno(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Aluno() {
      matricula_ = 0;
      nome_ = "";
      email_ = "";
      telefones_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Aluno(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              matricula_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nome_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                telefones_ = new java.util.ArrayList<br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone>();
                mutable_bitField0_ |= 0x00000008;
              }
              telefones_.add(
                  input.readMessage(br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          telefones_ = java.util.Collections.unmodifiableList(telefones_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.internal_static_ExemploProtocolBuffers_Aluno_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.internal_static_ExemploProtocolBuffers_Aluno_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno.class, br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno.Builder.class);
    }

    private int bitField0_;
    public static final int MATRICULA_FIELD_NUMBER = 1;
    private int matricula_;
    /**
     * <code>int32 matricula = 1;</code>
     */
    public int getMatricula() {
      return matricula_;
    }

    public static final int NOME_FIELD_NUMBER = 2;
    private volatile java.lang.Object nome_;
    /**
     * <code>string nome = 2;</code>
     */
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      }
    }
    /**
     * <code>string nome = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TELEFONES_FIELD_NUMBER = 4;
    private java.util.List<br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone> telefones_;
    /**
     * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
     */
    public java.util.List<br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone> getTelefonesList() {
      return telefones_;
    }
    /**
     * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
     */
    public java.util.List<? extends br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.TelefoneOrBuilder> 
        getTelefonesOrBuilderList() {
      return telefones_;
    }
    /**
     * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
     */
    public int getTelefonesCount() {
      return telefones_.size();
    }
    /**
     * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
     */
    public br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone getTelefones(int index) {
      return telefones_.get(index);
    }
    /**
     * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
     */
    public br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.TelefoneOrBuilder getTelefonesOrBuilder(
        int index) {
      return telefones_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (matricula_ != 0) {
        output.writeInt32(1, matricula_);
      }
      if (!getNomeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nome_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      for (int i = 0; i < telefones_.size(); i++) {
        output.writeMessage(4, telefones_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (matricula_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, matricula_);
      }
      if (!getNomeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nome_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      for (int i = 0; i < telefones_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, telefones_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno)) {
        return super.equals(obj);
      }
      br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno other = (br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno) obj;

      boolean result = true;
      result = result && (getMatricula()
          == other.getMatricula());
      result = result && getNome()
          .equals(other.getNome());
      result = result && getEmail()
          .equals(other.getEmail());
      result = result && getTelefonesList()
          .equals(other.getTelefonesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MATRICULA_FIELD_NUMBER;
      hash = (53 * hash) + getMatricula();
      hash = (37 * hash) + NOME_FIELD_NUMBER;
      hash = (53 * hash) + getNome().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      if (getTelefonesCount() > 0) {
        hash = (37 * hash) + TELEFONES_FIELD_NUMBER;
        hash = (53 * hash) + getTelefonesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ExemploProtocolBuffers.Aluno}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ExemploProtocolBuffers.Aluno)
        br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.AlunoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.internal_static_ExemploProtocolBuffers_Aluno_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.internal_static_ExemploProtocolBuffers_Aluno_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno.class, br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno.Builder.class);
      }

      // Construct using br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTelefonesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        matricula_ = 0;

        nome_ = "";

        email_ = "";

        if (telefonesBuilder_ == null) {
          telefones_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          telefonesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.internal_static_ExemploProtocolBuffers_Aluno_descriptor;
      }

      public br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno getDefaultInstanceForType() {
        return br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno.getDefaultInstance();
      }

      public br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno build() {
        br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno buildPartial() {
        br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno result = new br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.matricula_ = matricula_;
        result.nome_ = nome_;
        result.email_ = email_;
        if (telefonesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            telefones_ = java.util.Collections.unmodifiableList(telefones_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.telefones_ = telefones_;
        } else {
          result.telefones_ = telefonesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno) {
          return mergeFrom((br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno other) {
        if (other == br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno.getDefaultInstance()) return this;
        if (other.getMatricula() != 0) {
          setMatricula(other.getMatricula());
        }
        if (!other.getNome().isEmpty()) {
          nome_ = other.nome_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (telefonesBuilder_ == null) {
          if (!other.telefones_.isEmpty()) {
            if (telefones_.isEmpty()) {
              telefones_ = other.telefones_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureTelefonesIsMutable();
              telefones_.addAll(other.telefones_);
            }
            onChanged();
          }
        } else {
          if (!other.telefones_.isEmpty()) {
            if (telefonesBuilder_.isEmpty()) {
              telefonesBuilder_.dispose();
              telefonesBuilder_ = null;
              telefones_ = other.telefones_;
              bitField0_ = (bitField0_ & ~0x00000008);
              telefonesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTelefonesFieldBuilder() : null;
            } else {
              telefonesBuilder_.addAllMessages(other.telefones_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int matricula_ ;
      /**
       * <code>int32 matricula = 1;</code>
       */
      public int getMatricula() {
        return matricula_;
      }
      /**
       * <code>int32 matricula = 1;</code>
       */
      public Builder setMatricula(int value) {
        
        matricula_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 matricula = 1;</code>
       */
      public Builder clearMatricula() {
        
        matricula_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object nome_ = "";
      /**
       * <code>string nome = 2;</code>
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nome_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nome = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nome = 2;</code>
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 2;</code>
       */
      public Builder clearNome() {
        
        nome_ = getDefaultInstance().getNome();
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 2;</code>
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nome_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.util.List<br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone> telefones_ =
        java.util.Collections.emptyList();
      private void ensureTelefonesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          telefones_ = new java.util.ArrayList<br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone>(telefones_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone, br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone.Builder, br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.TelefoneOrBuilder> telefonesBuilder_;

      /**
       * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
       */
      public java.util.List<br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone> getTelefonesList() {
        if (telefonesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(telefones_);
        } else {
          return telefonesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
       */
      public int getTelefonesCount() {
        if (telefonesBuilder_ == null) {
          return telefones_.size();
        } else {
          return telefonesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
       */
      public br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone getTelefones(int index) {
        if (telefonesBuilder_ == null) {
          return telefones_.get(index);
        } else {
          return telefonesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
       */
      public Builder setTelefones(
          int index, br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone value) {
        if (telefonesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTelefonesIsMutable();
          telefones_.set(index, value);
          onChanged();
        } else {
          telefonesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
       */
      public Builder setTelefones(
          int index, br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone.Builder builderForValue) {
        if (telefonesBuilder_ == null) {
          ensureTelefonesIsMutable();
          telefones_.set(index, builderForValue.build());
          onChanged();
        } else {
          telefonesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
       */
      public Builder addTelefones(br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone value) {
        if (telefonesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTelefonesIsMutable();
          telefones_.add(value);
          onChanged();
        } else {
          telefonesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
       */
      public Builder addTelefones(
          int index, br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone value) {
        if (telefonesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTelefonesIsMutable();
          telefones_.add(index, value);
          onChanged();
        } else {
          telefonesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
       */
      public Builder addTelefones(
          br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone.Builder builderForValue) {
        if (telefonesBuilder_ == null) {
          ensureTelefonesIsMutable();
          telefones_.add(builderForValue.build());
          onChanged();
        } else {
          telefonesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
       */
      public Builder addTelefones(
          int index, br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone.Builder builderForValue) {
        if (telefonesBuilder_ == null) {
          ensureTelefonesIsMutable();
          telefones_.add(index, builderForValue.build());
          onChanged();
        } else {
          telefonesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
       */
      public Builder addAllTelefones(
          java.lang.Iterable<? extends br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone> values) {
        if (telefonesBuilder_ == null) {
          ensureTelefonesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, telefones_);
          onChanged();
        } else {
          telefonesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
       */
      public Builder clearTelefones() {
        if (telefonesBuilder_ == null) {
          telefones_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          telefonesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
       */
      public Builder removeTelefones(int index) {
        if (telefonesBuilder_ == null) {
          ensureTelefonesIsMutable();
          telefones_.remove(index);
          onChanged();
        } else {
          telefonesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
       */
      public br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone.Builder getTelefonesBuilder(
          int index) {
        return getTelefonesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
       */
      public br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.TelefoneOrBuilder getTelefonesOrBuilder(
          int index) {
        if (telefonesBuilder_ == null) {
          return telefones_.get(index);  } else {
          return telefonesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
       */
      public java.util.List<? extends br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.TelefoneOrBuilder> 
           getTelefonesOrBuilderList() {
        if (telefonesBuilder_ != null) {
          return telefonesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(telefones_);
        }
      }
      /**
       * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
       */
      public br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone.Builder addTelefonesBuilder() {
        return getTelefonesFieldBuilder().addBuilder(
            br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone.getDefaultInstance());
      }
      /**
       * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
       */
      public br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone.Builder addTelefonesBuilder(
          int index) {
        return getTelefonesFieldBuilder().addBuilder(
            index, br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone.getDefaultInstance());
      }
      /**
       * <code>repeated .ExemploProtocolBuffers.Telefone telefones = 4;</code>
       */
      public java.util.List<br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone.Builder> 
           getTelefonesBuilderList() {
        return getTelefonesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone, br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone.Builder, br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.TelefoneOrBuilder> 
          getTelefonesFieldBuilder() {
        if (telefonesBuilder_ == null) {
          telefonesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone, br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone.Builder, br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.TelefoneOrBuilder>(
                  telefones_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          telefones_ = null;
        }
        return telefonesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ExemploProtocolBuffers.Aluno)
    }

    // @@protoc_insertion_point(class_scope:ExemploProtocolBuffers.Aluno)
    private static final br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno();
    }

    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Aluno>
        PARSER = new com.google.protobuf.AbstractParser<Aluno>() {
      public Aluno parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Aluno(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Aluno> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Aluno> getParserForType() {
      return PARSER;
    }

    public br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Aluno getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TelefoneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ExemploProtocolBuffers.Telefone)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string numero = 1;</code>
     */
    java.lang.String getNumero();
    /**
     * <code>string numero = 1;</code>
     */
    com.google.protobuf.ByteString
        getNumeroBytes();

    /**
     * <code>.ExemploProtocolBuffers.Tipo tipo = 2;</code>
     */
    int getTipoValue();
    /**
     * <code>.ExemploProtocolBuffers.Tipo tipo = 2;</code>
     */
    br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Tipo getTipo();
  }
  /**
   * Protobuf type {@code ExemploProtocolBuffers.Telefone}
   */
  public  static final class Telefone extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ExemploProtocolBuffers.Telefone)
      TelefoneOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Telefone.newBuilder() to construct.
    private Telefone(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Telefone() {
      numero_ = "";
      tipo_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Telefone(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              numero_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              tipo_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.internal_static_ExemploProtocolBuffers_Telefone_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.internal_static_ExemploProtocolBuffers_Telefone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone.class, br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone.Builder.class);
    }

    public static final int NUMERO_FIELD_NUMBER = 1;
    private volatile java.lang.Object numero_;
    /**
     * <code>string numero = 1;</code>
     */
    public java.lang.String getNumero() {
      java.lang.Object ref = numero_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        numero_ = s;
        return s;
      }
    }
    /**
     * <code>string numero = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNumeroBytes() {
      java.lang.Object ref = numero_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        numero_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIPO_FIELD_NUMBER = 2;
    private int tipo_;
    /**
     * <code>.ExemploProtocolBuffers.Tipo tipo = 2;</code>
     */
    public int getTipoValue() {
      return tipo_;
    }
    /**
     * <code>.ExemploProtocolBuffers.Tipo tipo = 2;</code>
     */
    public br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Tipo getTipo() {
      br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Tipo result = br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Tipo.valueOf(tipo_);
      return result == null ? br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Tipo.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNumeroBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, numero_);
      }
      if (tipo_ != br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Tipo.MOVEL.getNumber()) {
        output.writeEnum(2, tipo_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNumeroBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, numero_);
      }
      if (tipo_ != br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Tipo.MOVEL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, tipo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone)) {
        return super.equals(obj);
      }
      br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone other = (br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone) obj;

      boolean result = true;
      result = result && getNumero()
          .equals(other.getNumero());
      result = result && tipo_ == other.tipo_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMERO_FIELD_NUMBER;
      hash = (53 * hash) + getNumero().hashCode();
      hash = (37 * hash) + TIPO_FIELD_NUMBER;
      hash = (53 * hash) + tipo_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ExemploProtocolBuffers.Telefone}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ExemploProtocolBuffers.Telefone)
        br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.TelefoneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.internal_static_ExemploProtocolBuffers_Telefone_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.internal_static_ExemploProtocolBuffers_Telefone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone.class, br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone.Builder.class);
      }

      // Construct using br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        numero_ = "";

        tipo_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.internal_static_ExemploProtocolBuffers_Telefone_descriptor;
      }

      public br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone getDefaultInstanceForType() {
        return br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone.getDefaultInstance();
      }

      public br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone build() {
        br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone buildPartial() {
        br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone result = new br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone(this);
        result.numero_ = numero_;
        result.tipo_ = tipo_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone) {
          return mergeFrom((br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone other) {
        if (other == br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone.getDefaultInstance()) return this;
        if (!other.getNumero().isEmpty()) {
          numero_ = other.numero_;
          onChanged();
        }
        if (other.tipo_ != 0) {
          setTipoValue(other.getTipoValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object numero_ = "";
      /**
       * <code>string numero = 1;</code>
       */
      public java.lang.String getNumero() {
        java.lang.Object ref = numero_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          numero_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string numero = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNumeroBytes() {
        java.lang.Object ref = numero_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          numero_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string numero = 1;</code>
       */
      public Builder setNumero(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        numero_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string numero = 1;</code>
       */
      public Builder clearNumero() {
        
        numero_ = getDefaultInstance().getNumero();
        onChanged();
        return this;
      }
      /**
       * <code>string numero = 1;</code>
       */
      public Builder setNumeroBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        numero_ = value;
        onChanged();
        return this;
      }

      private int tipo_ = 0;
      /**
       * <code>.ExemploProtocolBuffers.Tipo tipo = 2;</code>
       */
      public int getTipoValue() {
        return tipo_;
      }
      /**
       * <code>.ExemploProtocolBuffers.Tipo tipo = 2;</code>
       */
      public Builder setTipoValue(int value) {
        tipo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ExemploProtocolBuffers.Tipo tipo = 2;</code>
       */
      public br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Tipo getTipo() {
        br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Tipo result = br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Tipo.valueOf(tipo_);
        return result == null ? br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Tipo.UNRECOGNIZED : result;
      }
      /**
       * <code>.ExemploProtocolBuffers.Tipo tipo = 2;</code>
       */
      public Builder setTipo(br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Tipo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        tipo_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ExemploProtocolBuffers.Tipo tipo = 2;</code>
       */
      public Builder clearTipo() {
        
        tipo_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ExemploProtocolBuffers.Telefone)
    }

    // @@protoc_insertion_point(class_scope:ExemploProtocolBuffers.Telefone)
    private static final br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone();
    }

    public static br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Telefone>
        PARSER = new com.google.protobuf.AbstractParser<Telefone>() {
      public Telefone parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Telefone(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Telefone> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Telefone> getParserForType() {
      return PARSER;
    }

    public br.ufs.dcomp.ExemploProtocolBuffers.ContatoProto.Telefone getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExemploProtocolBuffers_Aluno_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExemploProtocolBuffers_Aluno_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExemploProtocolBuffers_Telefone_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExemploProtocolBuffers_Telefone_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013aluno.proto\022\026ExemploProtocolBuffers\"l\n" +
      "\005Aluno\022\021\n\tmatricula\030\001 \001(\005\022\014\n\004nome\030\002 \001(\t\022" +
      "\r\n\005email\030\003 \001(\t\0223\n\ttelefones\030\004 \003(\0132 .Exem" +
      "ploProtocolBuffers.Telefone\"F\n\010Telefone\022" +
      "\016\n\006numero\030\001 \001(\t\022*\n\004tipo\030\002 \001(\0162\034.ExemploP" +
      "rotocolBuffers.Tipo*)\n\004Tipo\022\t\n\005MOVEL\020\000\022\010" +
      "\n\004CASA\020\001\022\014\n\010TRABALHO\020\002B3\n#br.ufs.dcomp.E" +
      "xemploProtocolBuffersB\014ContatoProtob\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ExemploProtocolBuffers_Aluno_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ExemploProtocolBuffers_Aluno_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExemploProtocolBuffers_Aluno_descriptor,
        new java.lang.String[] { "Matricula", "Nome", "Email", "Telefones", });
    internal_static_ExemploProtocolBuffers_Telefone_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ExemploProtocolBuffers_Telefone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExemploProtocolBuffers_Telefone_descriptor,
        new java.lang.String[] { "Numero", "Tipo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
